apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: craft-de-jet/spring-api
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:latest'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:123456789'
    local: {}
  deploy:
    helm:
      releases:
      - name: spring-api
        chartPath: charts/spring-api
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}'
          image.tag: '123456789'
